"""add_score_at_archive

Revision ID: 496f4cc37511
Revises: 6cbe1fde9218
Create Date: 2026-06-27 16:14:07.622676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496f4cc37511'
down_revision: Union[str, Sequence[str], None] = '6cbe1fde9218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('score_at_archive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'score_at_archive')
    # ### end Alembic commands ###
